### ISSUE TITLE
I am not able to load Netlogo

### ISSUE THREAD

**Issue by sdaza** [quaquel/pyNetLogo#1]
Hello, 

Nice package. I am trying to load NetLogo 6.0 on my Mac with no success. I get this error. Any ideas on what the problem might be?

```
import pyNetLogo as nl

path = '/Applications/NetLogo 6.0'

netlogo = nl.NetLogoLink(gui=False, netlogo_home=path, netlogo_version='6')
```

```
---------------------------------------------------------------------------
java.lang.RuntimeExceptionPyRaisable      Traceback (most recent call last)
<ipython-input-11-faf2fd1d0f65> in <module>()
----> 1 netlogo = nl.NetLogoLink(gui=False)

~/miniconda3/lib/python3.6/site-packages/pyNetLogo/core.py in __init__(self, gui, thd, netlogo_home, netlogo_version, jvm_home)
    225                 jpype.java.lang.System.setProperty('java.awt.headless', 'true')
    226 
--> 227         link = jpype.JClass(module_name[self.netlogo_version])
    228 
    229         if sys.platform == 'darwin' and gui:

~/miniconda3/lib/python3.6/site-packages/jpype/_jclass.py in JClass(name)
     53     jc = _jpype.findClass(name)
     54     if jc is None:
---> 55         raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
     56 
     57     return _getClassFor(jc)

java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class NetLogoLinkV6.NetLogoLink not found
```

**Comment by stevengogogo** [comment]
**# Class NetLogoLinkV6.NetLogoLink not found**

I have the same problem: Unable to link to Java class
---
System: High Sierrra 10.13.3; Envoriment: Anaconda3=4.4.10
Install Channel (library: channel): 
                    jpype1: conda-forge
              pynetlogo: pip

Error Message: "Class NetLogoLinkV6.NetLogoLink not found"
---

I solved the problem by using python and Java SDK which is installed by [brew](https://gist.github.com/tomysmile/a9a7aee85ff73454bd57e198ad90e614). Besides, I uninstall Anaconda. Here is what I did,
---
1. Uninstall Anaconda
2. I[nstall Homebrew to install Python3 ](http://docs.python-guide.org/en/latest/starting/install3/osx/)
3. Use Homebrew to install [Java](https://gist.github.com/tomysmile/a9a7aee85ff73454bd57e198ad90e614)
4. Download [Jpype](https://pypi.python.org/pypi/JPype1-py3)  and use command: sudo python3 setup.py install
5. Install pyNetLogo by: sudo pip3 install pynetlogo
--- 

Then, it works for me. The reason why Jpype, which pynetlogo needs, can't find Java class is because Java JDK is under system folder in Mac, and Jpype, pynetlogo are under anaconda3. Therefore, jpype can't find Java classpath.

**Comment by quaquel** [comment]
I am a mac user myself. The problem is with jpype rather than with pynetlogo. If JAVA_HOME is not set, jpype will use the system jvm, rather than a more recently installed version of java. One solution is to set JAVA_HOME explicitly. This however only works if you start python from the terminal. 

For debugging purposes, it might be useful to explicitly check what is returned by jpype.get_default_jvmpath(). Ensure this is a recent version of java. Once this works properly, try to load pynetlogo.
