### ISSUE TITLE
App doesn't terminate after NetLogo has been used (in a thread)

### ISSUE THREAD

**Issue by codingarmadillo** [quaquel/pyNetLogo#32]
I'm using pyNetLogo in a GUI app, so have it in a thread. However, when my app ends, it hangs. Looks like there's still some Java running. I've recreated the problem in a simple app.

```
import threading
import pyNetLogo

def do_work():
    netlogo = pyNetLogo.NetLogoLink(gui=False, netlogo_home="/opt/NetLogo/", netlogo_version="6.1")
    netlogo.kill_workspace()
    print("work completed")

def main():
    worker_thread = threading.Thread(target=do_work)
    worker_thread.start()

    worker_thread.join()

    print("closing down")

if __name__ == "__main__":
    main()
```

This application reaches and displays the "closing down" message, but it never returns control to the shell.

I believe there's still some Java code running as I've seen the following message appear if I don't kill the app for a few seconds after the "closing down" message.

```
Warning: Could not get charToByteConverterClass!
```

I created a similar test app using jpype that ran a simple java command. That was fine. Everything closed down as expected. So it seems to be something related to launching NetLogo.

Any ideas on how I can terminate NetLogo and have control return to the shell? By this point in the execution the app is ending, so I'd even be happy to nuke any threads/processes---if that's what it takes. Just need it to stop and return control to the shell.

I'm running Python 3.8.2, pyNetLogo 0.4.1 and jpype 0.7.4. Also tried with Python 3.7. Same issue.

My main development environment is Ubuntu 20.04, but I've experienced the same when testing in Windows 10.

**Comment by quaquel** [comment]
can you share the pure jpype example as well?

My hunch is that it has to do with kill_workspace only closing the model file but not netlogo itself.

**Comment by codingarmadillo** [comment]
Sure. Here's the JPype code.

```python
import threading
from jpype import startJVM, java, detachThreadFromJVM, shutdownJVM

def do_work():
    startJVM(convertStrings=False)

    java.lang.System.out.println("Hello from JPype")

    print("work completed")

    detachThreadFromJVM()

def main():
    worker_thread = threading.Thread(target=do_work)
    worker_thread.start()

    worker_thread.join()

    shutdownJVM()

    print("closing down")

if __name__ == "__main__":
    main()
```

**Comment by quaquel** [comment]
Not sure why your code does not work. I have been using pyNetLogo for large scale computational experimentation and it always closes down normally without a problem. I however always rely on multiprocessing rather than threading for this.

I am in the middle of online teaching, so time to dive into this is limited. A few things you might try:
1. kill_workspace invokes some java code which effectively calls the dispose method of the HeadlessWorkspace class 
(see http://ccl.northwestern.edu/netlogo/docs/scaladoc/org/nlogo/headless/HeadlessWorkspace.html#dispose():Unit ). So we are not calling detachTreadFromJVM() like you are doing in the pure jpype example. 
2. Searching on `Warning: Could not get charToByteConverterClass!` seems to suggest it might be a java version issue. Which jvm are you using?
3. What happens if you replace threading with multiprocessing in the test example?

**Comment by codingarmadillo** [comment]
Sorry for the late response---I got dragged into something else.

I'm using openjdk 11.0.7 2020-04-14.

I've not tried multiprocessing with it. I pondered that, or just shelling out to a new script, but it doesn't fit my requirement well.

I'd presume multiprocess will work as it's a separate process.

At present, it seems to work if I pause for 15 secs when closing down, so I'll stick with this for now. 

Thanks for the responses.
