### ISSUE TITLE
netlogo.report()

### ISSUE THREAD

**Issue by zargol7419** [quaquel/pyNetLogo#57]
Hi, 
I am using pynetlogo package to write and read some attributes for my agents. In my NetLogo model, I have assigned 156 wells as agents, and each one has its own flow rate named Debi. As you can see in the attached picture, I have defined Debi using matrix extension and I wanna use pynetlogo to read this matrix and save it as a variable as I wanna import this variable in another software named Modflow to run an existing model then report the results.
![image](https://user-images.githubusercontent.com/103249900/185739728-e8f72b34-c993-4eab-84a0-2e8399e9087d.png)

I tried    -----> Debiwel = netlogo.report('map [s -> [Debi] of s] sort wels') code to receive Debi variable but I got this error:
![image](https://user-images.githubusercontent.com/103249900/185739768-ea4c0bac-171d-4035-9731-e793d0a63a25.png)
Is it possible to get a matrix attribute from NetLogo using NetLogo.report ? What should I do to execute the aforementioned process?
Thanks in advance for your answering. I appreciate it.

**Comment by EwoutH** [comment]
@zargol7419 Thanks for filing this issue. I believe currently it isn't possible to report matrices from the NetLogo matrix extensions using PyNetLogo.

@quaquel Currently we probably don't support reporting NetLogo [matrices](https://ccl.northwestern.edu/netlogo/docs/matrix.html) with PyNetlogo right? How complicated would it be to add a feature that can report a NetLogo matrix as some Python data type (probably NumPy array or Pandas dataframe)?

The code for the NetLogo Matrix Extension [is here](https://github.com/NetLogo/Matrix-Extension/blob/hexy/src/main/java/MatrixExtension.java).

**Comment by quaquel** [comment]
Sorry to have missed this issue last summer. For combining netlogo and modflow, I would suggest you first check [A coupled simulation architecture for agent-based/geohydrological modelling with NetLogo and MODFLOW](https://www.sciencedirect.com/science/article/pii/S136481521930091X). In fact, pynetlogo emerged out of this research. 

The current exchange of information between pynetlogo and NetLogo is based on automagically casting the results from its java datatype to the equivalent python datatype. Your error indicates that this does not work correctly in the case of NetLogo matrices. A simple work around would be to write the matrix to a csv file or something similar and read that from the python side. On the python side, rather than using report, you would issue a command to write the text file to a given path. Next, you can simply read the file on the python side.

Alternatively, with a minimum example of a NetLogo model and matrices, I can look into the java code for converting this, but I don't know exactly when I will have time to look into that.

Don't hesitate to ask if you have any follow up questions.

**Comment by zargol7419** [comment]
It's Ok, during this time I was working on my Modflow model. Yes I know, I have been inspired by your article for my thesis project that's why I am using Pynetlogo!  so I have read it before and it is one of my references.
Thank you so much for your suggestion. I am going to implement it.
@quaquel @EwoutH Thank you both for your answers. I appreciate it.

**Comment by EwoutH** [comment]
You're welcome! Please let us know how it works out, so others can use your insights/solution.
