### ISSUE TITLE
Import and attribute errors in tests

### ISSUE THREAD

**Issue by EwoutH** [quaquel/pyNetLogo#59]
@quaquel I'm trying to get the tests working again, and migrating from Travis CI to GitHub Actions, before doing some modernizations on pyNetlogo. However, currently an ModuleNotFoundError appears:

```
ERROR: Failure: ModuleNotFoundError (No module named 'pyNetLogo.pyNetLogo')
```
This error happens here in the tests:
https://github.com/quaquel/pyNetLogo/blob/55431ddb3c75c5dec41855fca874fbc7e9034ce1/tests/test_netlogo.py#L15

I tried doing just `import pyNetLogo`, like this:
```diff
- import pyNetLogo.pyNetLogo as pyNetLogo 
+ import pyNetLogo
```
But that also failed,
```
E           AttributeError: <module 'pyNetLogo' from '/home/runner/work/pyNetLogo/pyNetLogo/pyNetLogo/__init__.py'> does not have the attribute 'os'
```
a few lines further:

https://github.com/quaquel/pyNetLogo/blob/55431ddb3c75c5dec41855fca874fbc7e9034ce1/tests/test_netlogo.py#L20

I also tried changing it in `@mock.patch('pyNetLogo.os')`:

```diff
-     @mock.patch('pyNetLogo.pyNetLogo.os')
+     @mock.patch('pyNetLogo.os')
```
But it fails with the same error.

Do you have any idea how to fix the tests?

**Comment by quaquel** [comment]
As you might have seen, I made some progress over the last few days. `setup.py` has moved to `pyproject.toml`, and basic Github actions have been set up. The main open question is how to do CI. Specifically, do we want to test against NetLogo itself or mock out all interactions with NetLogo? We can in principle, test against NetLogo because we can install NetLogo as part of the CI environment. The main issue will be in that case to have suitable models available to use for testing.
